parameters:

services:
  _defaults:
    autowire: true

  #~ Application source code
  Application\:
    resource: '../../src/*'

  console.output.stdout:
    class:   'Eureka\Component\Console\Output\StreamOutput'
    factory: ['Application\Service\OutputFactory', 'stdout']

  Eureka\Component\Console\Terminal\Terminal:
    arguments:
      $output: '@console.output.stdout'
